server:
  port: 8100

spring:
  application:
    name: 4cast
  datasource:
    driver-class-name=oracle: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: forecast
    password: abc123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

api:
  version: 1.0

swagger:
  enabled: true
  title: 4cast API
  description: Forecast Test Project
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false